# Generated by Django 3.0.8 on 2020-08-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_class_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyWebSiteOffer',
            new_name='TutorialCourses',
        ),
    ]
