# Generated by Django 3.0.8 on 2020-08-01 12:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_class_app', '0002_auto_20200801_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcourses',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Published'),
            preserve_default=False,
        ),
    ]
