# Generated by Django 3.0.8 on 2020-08-01 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_class_app', '0003_tutorialcourses_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialcourses',
            name='course_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=12),
            preserve_default=False,
        ),
    ]
