# Generated by Django 3.0.8 on 2020-08-04 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_class_app', '0004_tutorialcourses_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
        ),
    ]
