# Generated by Django 3.0.8 on 2020-09-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_class_app', '0006_coursedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialcourses',
            name='course_title',
            field=models.CharField(choices=[('MAN', 'MAN'), ('WOM', 'WOM'), ('GIR', 'GIR')], max_length=20),
        ),
    ]
