# Generated by Django 3.0.8 on 2020-09-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_class_app', '0007_auto_20200901_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialcourses',
            name='course_title',
            field=models.CharField(max_length=20),
        ),
    ]
