# Generated by Django 3.0.8 on 2020-09-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_class_app', '0008_auto_20200901_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSetModelForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
